import glob
import os
import re
import sys
import time
import yaml
import logging
from datetime import datetime

from .excel import load_pmcs_excel

__all__ = [
    "get_latest_pmcs_path",
    "get_local_data_path",
    "write_output",
    "format_latex",
    "load_milestones",
]

# Input filename format:
#
# YYYYMM-<datatype>.xls
#
# Where YYYY is the year, MM is the month and <datatype> is either "BL" (for
# baseline) or "ME" (for forecast).


def get_latest_pmcs_path(path=None):
    """By default, fetch the latest forecast.
    """
    if not path:
        path = os.path.normpath(
            os.path.join(os.path.dirname(__file__), "..", "data", "pmcs")
        )
    return sorted(glob.glob(os.path.join(path, "??????-ME.xls")))[-1]


def get_local_data_path(path=os.path.dirname(__file__)):
    return os.path.normpath(
        os.path.join(os.path.dirname(__file__), "..", "data", "local.yaml")
    )


def write_output(filename, content, comment_prefix="%"):
    print(f"Writing output to {filename}")
    with open(filename, "w") as f:
        f.write(
            f"{comment_prefix} Auto-generated by {sys.argv[0]} "
            f"on {time.strftime('%c')} - DO NOT EDIT\n\n"
        )
        f.write(content)


def format_latex(
    text,
    cite_handles=[
        "LDM",
        "DMTN",
        "SQR",
        "PSTN",
        "SMTN",
        "LSE",
        "LDO",
        "LOO",
        "LDF",
        "LSO",
        "LEP",
        "LSP",
        "OPSTN",
        "TEST",
    ],
):
    # Automatically add citations to anything that looks like a document
    # (Handle-NNN), unless it looks like a milestone (LDM-503-nn).
    return re.sub(
        f"(({'|'.join(cite_handles)})-\\d{{3}})(?!(?<=LDM-\\d{{3}})-\\w)",
        r"\\citeds{\1}",
        text.strip()
        .replace("#", r"\#")
        .replace("&", r"\&")
        .replace("Test report: ", ""),
    )


def load_milestones(pmcs_filename, local_data_filename):
    logger = logging.getLogger(__name__)

    logger.info(f"Loading PMCS data from: {pmcs_filename}")
    logger.info(f"Loading local annotations from: {local_data_filename}")
    milestones = load_pmcs_excel(pmcs_filename)

    with open(local_data_filename) as f:
        local = yaml.safe_load(f)
    for ms in milestones:
        if ms.code in local:
            # These are core PMCS attributes; we should warn if we
            # over-write them.
            for attribute in ["name", "wbs", "level", "predecessors", "successors"]:
                if attribute in local[ms.code]:
                    logger.warning(
                        f"Overriding PMCS {attribute} on {ms.code} "
                        f"(was “{getattr(ms, attribute)}”; "
                        f"now “{local[ms.code][attribute]}”)"
                    )
                    setattr(ms, attribute, local[ms.code][attribute])

            for attribute in ["due", "completed"]:
                if attribute in local[ms.code]:
                    logger.warning(
                        f"Overriding PMCS {attribute} on {ms.code} "
                        f"(was {getattr(ms, attribute)}; "
                        f"now {local[ms.code][attribute]})"
                    )
                    if local[ms.code][attribute] == "":
                        setattr(ms, attribute, None)
                    else:
                        setattr(
                            ms,
                            attribute,
                            datetime.strptime(local[ms.code][attribute], "%Y-%m-%d"),
                        )

            for attribute in [
                "aka",
                "description",
                "comment",
                "short_name",
                "test_spec",
                "jira",
                "jira_testplan",
            ]:
                if attribute in local[ms.code]:
                    logger.info(f"Setting {attribute} on {ms.code}")
                    setattr(ms, attribute, local[ms.code][attribute])

    return milestones
