import glob
import os
import sys
import time

__all__ = ["get_latest_pmcs_path",
           "get_local_data_path",
           "write_output"]

# Input filename format:
#
# YYYYMM-<datatype>.xls
#
# Where YYYY is the year, MM is the month and <datatype> is either "BL" (for
# baseline) or "ME" (for forecast).

def get_latest_pmcs_path(path=None):
    """By default, fetch the latest forecast.
    """
    if not path:
        path = os.path.normpath(os.path.join(os.path.dirname(__file__),
                                             "..", "data", "pmcs"))
    return sorted(glob.glob(os.path.join(path, "??????-ME.xls")))[-1]

def get_local_data_path(path=os.path.dirname(__file__)):
    return os.path.normpath(os.path.join(os.path.dirname(__file__),
                                         "..", "data", "local.yaml"))

def write_output(filename, content, comment_prefix="%"):
    print(f"Writing output to {filename}")
    with open(filename, 'w') as f:
        f.write(f"{comment_prefix} Auto-generated by {sys.argv[0]} on {time.strftime('%c')} - DO NOT EDIT\n\n")
        f.write(content)
