name: Test LDM-503 generation

on:
    push:
        branches-ignore:
            - master
    pull_request:
        branches-ignore:
            - master

jobs:
  ldm-503-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out LFS files
        run: |
          git lfs install
          git config -f .lfsconfig lfs.url https://git-lfs.lsst.codes
          git lfs pull
      - uses: actions/setup-python@v2
        with:
        python-version: 3.7

      - name: Install TeXLive
        run: |
          sudo apt-get update
          sudo apt-get -y install texlive texlive-pictures texlive-latex-extra texlive-fonts-extra latexmk

      - name: Check out LDM-503 source
        run: GIT_LFS_SKIP_SMUDGE=1 git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/lsst/ldm-503.git

      - name: Replace LDM-503 milestones submodule
        run: |
          rm -rf milestones
          ln -s .. ./milestones
        working-directory: ./ldm-503

      - name: Build LDM-503

        run: make
        working-directory: ./ldm-503

      - name: Upload resulting document as artifact
        uses: actions/upload-artifact@v2
        with:
          name: LDM-503 PDF
          path: ./ldm-503/LDM-503.pdf
