name: Code Linting

on: [push, pull_request]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint
      run: |
        flake8

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yamllint
    - name: Lint
      run: |
        # indent-sequence: whatever needed to match pyyaml output
        yamllint -s -d "{extends: default, rules: {line-length: {max: 100}, indentation: {spaces: consistent, indent-sequences: whatever}}}" data/local.yaml
