name: Trigger document updates

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [lsst-dm/dmtn-158, lsst/ldm-564, lsst/ldm-503]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ROBO_JDS_PAT }}
          repository: ${{ matrix.repo }}
          fetch-depth: 0
          submodules: true

      - name: Update milestones submodule
        run: git submodule update --remote --force milestones

      - name: Create commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add milestones
          git commit -m "Update milestones submodule"

      - name: Get date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u "+%Y-%m-%d %H:%M:%S")"
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ROBO_JDS_PAT }}
          branch: update-milestones
          branch-suffix: short-commit-hash
          title: Automatic milestone submodule update, ${{ steps.get-date.outputs.date }}
