name: Trigger document updates

on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [lsst-dm/dmtn-158]
    steps:
      - name: Trigger ${{ matrix.repo }} update
        run: |
          curl --request POST \
          --header "Accept: application/vnd.github.v3+json" \
          --data '{"ref": "master"}' \
          --header 'authorization: Bearer ${{ secrets.DOC_UPDATE }}' \
          https://api.github.com/repos/${{ matrix.repo }}/actions/workflows/update-milestones.yaml/dispatches
