name: Trigger document updates

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [lsst-dm/dmtn-232]
        #repo: [lsst-dm/dmtn-158, lsst/ldm-564, lsst/ldm-503, lsst-dm/dmtn-232]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WOM_MILESTONES_PAT }}
          repository: ${{ matrix.repo }}
          fetch-depth: 0
          submodules: true

      - name: Update milestones submodule
        run: git submodule update --remote --force milestones

      - name: Create commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add milestones
          git commit -m "Update milestones submodule"

      - name: Get date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u "+%Y-%m-%d %H:%M:%S")"
        shell: bash

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WOM_MILESTONES_PAT }}
          #IF i leave someone needs to make a new PAT
          branch: update-milestones
          branch-suffix: short-commit-hash
          title: Automatic milestone submodule update, ${{ steps.get-date.outputs.date }}

      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v1
        # requires branch protection
        with:
          token: ${{ secrets.WOM_MILESTONES_PAT }}
          repository: ${{ matrix.repo }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
